id: P001773
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1PD137818
  title: བོད་བཙན་པོའི་རྒྱལ་རབས་ཀྱི་ཆབ་སྲིད་ལམ་ལུགས་ཞིབ་འཇུག
  author: ''
  volumes:
    3a15d7343028452c891daf8933e2ef12:
      image_group_id: I4PD4215
      title: ''
      volume_number: 1
      total_pages: 378
      base_file: v001.txt
